[package]
name = "shallot"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
shallot_components = { path = "../shallot_components" }
shallot_foundation = { path = "../shallot_foundation" }

